### ISSUE TITLE
Migrate Github auth to use header for auth instead of query param

### ISSUE THREAD

**Issue by wzulfikar** [gumroad/wilfred#18]
Github is deprecating API authentication through query parameters which Wilfred is using. This issue will be the entry point of works related to migrating the auth from query param to header, as suggested by Github:

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/#changes-to-make

![Untitled.png](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F5ad54dc5-a273-4f5f-83d9-f1b53a8bbfe5%2FUntitled.png?table=block&id=c14e1935-d6bc-423a-ba42-ab287301c22e)

**Comment by slavingia** [comment]
Any progress on this?

**Comment by wzulfikar** [comment]
I researched on this sometimes ago but haven't applied any changes yet. Based on my finding, the suggested solution is to bump omniauth-github to >=1.4.0 where the issue is fixed (see: https://github.com/omniauth/omniauth-github/pull/84). So here's the todo:

- [ ] 1. Bump omniauth-github to 1.4.0
- [ ] 2. Make sure that Github doesn't complain
- [ ] 3. Send PR

**Comment by wzulfikar** [comment]
Since I haven't done anything yet, it should be fine if you want to reassign this (it's kind of good-first-task). Otherwise i'll continue when i'm free.

**Comment by wzulfikar** [comment]
Update: I'm doing this task for this week.

**Comment by slavingia** [comment]
@wzulfikar any luck?
