### ISSUE TITLE
Set up automatic deployments connected to the master branch

### ISSUE THREAD

**Issue by sharang-d** [gumroad/wilfred#32]
Vipul had made the connection earlier and I removed him so the connection broke.
I tried to connect on my own but I don't have admin access to this repo so it didn't work.

So either grant admin access to @gumroad/administrators for this repo or set up the integration @ https://dashboard.heroku.com/apps/wilfredapp/deploy/github.

@slavingia _a

**Comment by vishaltelangre** [comment]
I also tried it and it didn't work for the `developers` account (whose credentials are in 1Pass).

**Comment by slavingia** [comment]
added as admins

**Comment by sharang-d** [comment]
Fixed!
